### ISSUE TITLE
RFC: Change a few default modes

### ISSUE THREAD

**Issue by AdamNiederer** [CodeFalling/vue-mode#19]
Hello again,

I recently authored a few packages for editing Vue templates and sass under MMM-mode. Currently, the default web-mode and html-mode don't highlight vue-specific syntax very well, and sass-mode is almost completely broken.

Would pulling one or both of those packages as dependencies and making them the defaults be a welcome change?

The modes:
https://github.com/AdamNiederer/vue-html-mode
https://github.com/AdamNiederer/ssass-mode

**Comment by CodeFalling** [comment]
Yes of course, could you make a PR for this?

**Comment by AdamNiederer** [comment]
I'll get 'em both in one go once ssass-mode is accepted into MELPA. That should only take a few days.

**Comment by AdamNiederer** [comment]
Resolved in #21
