### ISSUE TITLE
<script> and <style> blocks not getting parsed

### ISSUE THREAD

**Issue by christabella** [CodeFalling/vue-mode#27]
My `<template>` contents syntax highlighting is working but the contents of `<script>` and `<style>` are completely not getting parsed. Am not using Spacemacs, and this is in my `init.el`:

```
(use-package vue-mode
  :ensure t
  :init
  :config
  (require 'vue-mode)
  (setq mmm-submode-decoration-level 2))
```

![image](https://cloud.githubusercontent.com/assets/2038751/24542008/90d149a6-162c-11e7-9a9a-85ec8325769c.png)

**Comment by aardito2** [comment]
`<script>` blocks are only parsed for me if I explicitly specify `<script lang="js">`. Looking at the regex used in the source, it seems like this is working as intended, but I'm not really sure why it should be necessary to do this.
