### ISSUE TITLE
No file named packages or package.el

### ISSUE THREAD

**Issue by kxxoling** [CodeFalling/vue-mode#3]
It's said to add config to file packages and package.el, but I only find packages.el in my .emacs.d directory. Is this a typo?

Not work if I add both lines to packages.el.

**Comment by CodeFalling** [comment]
It's for **spacemacs** user.

BTW, [web-mode](http://web-mode.org/) maybe a better choice.

**Comment by kxxoling** [comment]
我用的就是 Spacemacs，在微博上看到了另一种配法，都写在 .spacemacs 里面了，安装的时候报错说没有 mmm-mode，不过终于是支持 vue 文件的高亮了。但是自动补全和缩进行为有问题。
